//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interpol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сriminals
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public string Сharges { get; set; }
        public string UrlFoto { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Languages { get; set; }
        public string Nationality { get; set; }
    }
}
